### ISSUE TITLE
Apache Spark in a project

### ISSUE THREAD

**Issue by Juk3n** [Inkweto/back#5]
https://hub.docker.com/r/bitnami/spark/

**Comment by arczi1** [comment]
Research: 
https://hub.docker.com/r/bitnami/spark/
https://towardsdatascience.com/diy-apache-spark-docker-bb4f11c10d24
https://github.com/mjhea0/flask-spark-docker
https://www.kdnuggets.com/2020/07/apache-spark-cluster-docker.html

**Comment by Juk3n** [comment]
https://github.com/big-data-europe/docker-spark/issues/56

**Comment by szyminson** [comment]
This approach might be useful in case of running log search and retrieving results from inside of the flask app:
https://qbox.io/blog/asynchronous-apache-spark-flask-celery-elasticsearch
